server:
  port: 8081

spring:
  application:
    name: dr--r--r--
  main:
    allow-bean-definition-overriding: true
  config:
    import: classpath:security-storage-api/config/config.yml
  docker:
    compose:
      file: classpath:docker/docker-compose.yaml
      #서버가 켜지면 컨테이너들이 켜지고 꺼지면 알아서 꺼지나 필요할 때만 주석 제거
      lifecycle-management: start_only
  batch:
    jdbc:
      initialize-schema: ALWAYS
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: classpath:security-storage-api/social/github/github.key
            client-secret: classpath:security-storage-api/social/github/github.pub
            redirect-uri: http://localhost:8081/
          kakao:
            client-id: classpath:security-storage-api/social/kakao/client_id.key
            redirect-uri: http://localhost:8081/
            client-authentication-method: POST
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
kakao:
  private.key: classpath:security-storage-api/social/kakao/client_id.key

jwt:
  private.key: classpath:security-storage-api/jwt/jwt.key
  public.key: classpath:security-storage-api/jwt/jwt.pub
