server:
  port: 8080

spring:
  profiles:
    activate:
      on-profile: local
  quartz:
    job-store-type: memory
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/baemin
    username: sa
    password:
    driverClassName: org.h2.Driver
    hikari:
      connection-timeout: 300000

  jpa:
    hibernate:
      #애플리케이션 로딩 시점에 다 드랍하고 다시 생성
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        use_sql_comments: true
  batch:
    jdbc:
      initialize-schema: ALWAYS

logging:
  level:
    org.springframework.batch: DEBUG
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG