server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
vapid:
  public.key : classpath:security-storage-infra/vapid.pub
  private.key : classpath:security-storage-infra/vapid.key